export const citiesByDepartment: Record<string, string[]> = {
  Amazonas: ["Leticia", "Puerto Nariño"],
  Antioquia: [
    "Medellín",
    "Bello",
    "Itagüí",
    "Envigado",
    "Rionegro",
    "Apartadó",
    "Turbo",
    "Sabaneta",
    "La Estrella",
    "Caldas",
    "Copacabana",
    "Girardota",
    "Caucasia",
    "Yarumal",
    "Marinilla",
    "Santa Fe de Antioquia",
    "Sonsón",
    "Yolombó",
  ],
  Arauca: ["Arauca", "Saravena", "Tame", "Fortul", "Arauquita"],
  Atlántico: [
    "Barranquilla",
    "Soledad",
    "Malambo",
    "Sabanalarga",
    "Puerto Colombia",
    "Galapa",
    "Baranoa",
    "Sabanagrande",
    "Santo Tomás",
  ],
  "Bogotá D.C.": ["Bogotá"],
  Bolívar: [
    "Cartagena",
    "Magangué",
    "Turbaco",
    "Arjona",
    "Carmen de Bolívar",
    "Mompox",
    "San Pablo",
    "Santa Rosa",
    "San Juan Nepomuceno",
  ],
  Boyacá: [
    "Tunja",
    "Duitama",
    "Sogamoso",
    "Chiquinquirá",
    "Paipa",
    "Villa de Leyva",
    "Puerto Boyacá",
    "Moniquirá",
    "Garagoa",
    "Soatá",
  ],
  Caldas: [
    "Manizales",
    "La Dorada",
    "Chinchiná",
    "Villamaría",
    "Riosucio",
    "Anserma",
    "Salamina",
    "Aguadas",
    "Pensilvania",
  ],
  Caquetá: [
    "Florencia",
    "San Vicente del Caguán",
    "Belén de los Andaquíes",
    "Puerto Rico",
    "El Doncello",
  ],
  Casanare: [
    "Yopal",
    "Aguazul",
    "Villanueva",
    "Tauramena",
    "Paz de Ariporo",
    "Monterrey",
  ],
  Cauca: [
    "Popayán",
    "Santander de Quilichao",
    "Patía",
    "Puerto Tejada",
    "Guapi",
    "Piendamó",
    "Caloto",
  ],
  Cesar: [
    "Valledupar",
    "Aguachica",
    "Bosconia",
    "Codazzi",
    "Curumaní",
    "La Jagua de Ibirico",
    "La Paz",
    "Pueblo Bello",
  ],
  Chocó: ["Quibdó", "Istmina", "Tadó", "Riosucio", "Bahía Solano", "Acandí"],
  Córdoba: [
    "Montería",
    "Lorica",
    "Cereté",
    "Sahagún",
    "Montelíbano",
    "Planeta Rica",
    "Tierralta",
    "San Andrés de Sotavento",
  ],
  Cundinamarca: [
    "Soacha",
    "Facatativá",
    "Zipaquirá",
    "Chía",
    "Mosquera",
    "Fusagasugá",
    "Madrid",
    "Funza",
    "Cajicá",
    "Girardot",
    "Cota",
    "La Calera",
    "Sopó",
    "Tocancipá",
    "Tenjo",
    "Sibaté",
    "El Rosal",
    "Subachoque",
  ],
  Guainía: ["Inírida"],
  Guaviare: ["San José del Guaviare", "Calamar", "El Retorno", "Miraflores"],
  Huila: [
    "Neiva",
    "Pitalito",
    "Garzón",
    "La Plata",
    "Campoalegre",
    "Aipe",
    "Gigante",
    "San Agustín",
  ],
  "La Guajira": [
    "Riohacha",
    "Maicao",
    "Uribia",
    "San Juan del Cesar",
    "Manaure",
    "Fonseca",
    "Villanueva",
  ],
  Magdalena: [
    "Santa Marta",
    "Ciénaga",
    "Fundación",
    "El Banco",
    "Plato",
    "Aracataca",
    "Pivijay",
    "Zona Bananera",
  ],
  Meta: [
    "Villavicencio",
    "Acacías",
    "Granada",
    "Puerto López",
    "San Martín",
    "Restrepo",
    "Cumaral",
    "Puerto Gaitán",
  ],
  Nariño: [
    "Pasto",
    "Tumaco",
    "Ipiales",
    "Túquerres",
    "Samaniego",
    "La Unión",
    "Buesaco",
    "Sandoná",
  ],
  "Norte de Santander": [
    "Cúcuta",
    "Ocaña",
    "Pamplona",
    "Villa del Rosario",
    "Los Patios",
    "Tibú",
    "El Zulia",
  ],
  Putumayo: [
    "Mocoa",
    "Puerto Asís",
    "Orito",
    "Sibundoy",
    "Valle del Guamuez",
    "Villagarzón",
  ],
  Quindío: [
    "Armenia",
    "Calarcá",
    "Quimbaya",
    "Montenegro",
    "La Tebaida",
    "Circasia",
    "Filandia",
    "Salento",
  ],
  Risaralda: [
    "Pereira",
    "Dosquebradas",
    "Santa Rosa de Cabal",
    "La Virginia",
    "Belén de Umbría",
    "Quinchía",
  ],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
  Santander: [
    "Bucaramanga",
    "Floridablanca",
    "Girón",
    "Piedecuesta",
    "Barrancabermeja",
    "San Gil",
    "Socorro",
    "Málaga",
    "Lebrija",
    "Vélez",
    "Zapatoca",
  ],
  Sucre: [
    "Sincelejo",
    "Corozal",
    "Sampués",
    "Tolú",
    "San Marcos",
    "Coveñas",
    "San Onofre",
  ],
  Tolima: [
    "Ibagué",
    "Espinal",
    "Honda",
    "Mariquita",
    "Líbano",
    "Melgar",
    "Chaparral",
    "Purificación",
    "Ortega",
  ],
  "Valle del Cauca": [
    "Cali",
    "Buenaventura",
    "Palmira",
    "Buga",
    "Tuluá",
    "Cartago",
    "Yumbo",
    "Jamundí",
    "Candelaria",
    "Florida",
    "Pradera",
    "Sevilla",
    "Roldanillo",
    "Zarzal",
    "La Unión",
  ],
  Vaupés: ["Mitú", "Carurú", "Taraira"],
  Vichada: ["Puerto Carreño", "La Primavera", "Santa Rosalía", "Cumaribo"],
};
